/N03/det/setAbsMat G4_WATER
/N03/det/setAbsThick 20 cm
/N03/det/setGapMat G4_WATER      
/N03/det/setGapThick 0.001 mm    
/N03/det/setNbOfLayers 1         

# 1. Inizializza il run manager
/run/initialize

# 4. Disattiva il processo ionInelastic per il GenericIon
/process/inactivate ionInelastic

# 2. DEFINIZIONE DEL FASCIO CON PARTICLE GUN (Invece di GPS)
/gps/particle ion
/gps/ion 6 12 0
/gps/ene/type Mono
/gps/ene/mono 3000 MeV

# Nota: se il tuo Gun spara lungo l'asse X, lasciamo queste posizioni. 
# Se le altre macro usavano coordinate diverse (es. asse Z), usa quelle delle macro che hanno funzionato!
/gps/position -10 0 0 cm
/gps/direction 1 0 0

# 3. Ora definiamo lo scorer in sicurezza
/score/create/boxMesh BraggMesh
/score/mesh/boxSize 10 10 10 cm
/score/mesh/nBin 400 1 1
/score/quantity/energyDeposit edep
/score/close

# 5. Lancia la simulazione
/run/beamOn 10000
/score/dumpQuantityToFile BraggMesh edep carbon_FTFP_BERT_EMZ_noInelastic.csv