# Configura il phantom come un unico blocco di acqua omogeneo
/N03/det/setAbsMat G4_WATER
/N03/det/setAbsThick 1 mm
/N03/det/setGapMat G4_WATER         # Sostituisce l'Argon con l'Acqua
/N03/det/setGapThick 0.001 mm       # Riduce il gap a un valore infinitesimo
/N03/det/setNbOfLayers 200          # Imposta 200 strati per ottenere un fantoccio di 20 cm

# Inizializza il run manager e i thread worker
/run/initialize

# Disattiva il processo prima che il fascio parta
/process/inactivate ionInelastic

# Configurazione del fascio di Carbonio-12 con GPS
/gps/particle ion
/gps/ion 6 12 0
/gps/ene/type Mono
/gps/ene/mono 3000 MeV              # 1440 MeV per avere 120 MeV/u (3000 Mev per avere 250 MeV/u)

/gps/pos/type Point
/gps/pos/centre -10 0 0 cm
/gps/direction 1 0 0

# Lancia la simulazione ad alta statistica
/run/beamOn 1000000
