# $Id: run.mac 100674 2016-10-31 10:43:40Z gcosmo $
#
# Macro file for "AnaEx01.cc"
# 
# can be run in batch, without graphic
# or interactively: Idle> /control/execute run.mac
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 2
#
/run/numberOfThreads 1
# initialize
/run/initialize
#
/random/setSeeds 123 456
#
/gps/verbose 2

/gps/particle gamma
/gps/position -10 0 0 cm
/gps/direction 1 0 0
/gps/energy 10 MeV
/run/beamOn 1
